plugins:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# Bundler adds frozen_string_literal automatically
Style/FrozenStringLiteralComment:
  Enabled: false

# This is not a Rails app, Time.now is fine
Rails/TimeZone:
  Enabled: false

# Documentation not required for this gem
Style/Documentation:
  Enabled: false

# Allow longer methods and blocks for setup code
Metrics/MethodLength:
  Max: 20
  Exclude:
    - "lib/missive/paginator.rb" # Complex pagination logic
    - "lib/missive/resources/drafts.rb" # Comprehensive API parameter handling

Metrics/BlockLength:
  Max: 50
  Exclude:
    - "spec/**/*"

Metrics/AbcSize:
  Max: 26
  Exclude:
    - "lib/missive/paginator.rb" # Complex pagination logic

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - "lib/missive/paginator.rb" # Complex pagination logic
    - "lib/missive/resources/contacts.rb" # Validation logic

Metrics/ClassLength:
  Max: 100
  Exclude:
    - "lib/missive/resources/drafts.rb" # Comprehensive Draft API implementation

Metrics/ParameterLists:
  Max: 5
  Exclude:
    - "lib/missive/resources/drafts.rb" # Draft API requires 28 parameters per spec

Metrics/PerceivedComplexity:
  Max: 8
  Exclude:
    - "lib/missive/paginator.rb" # Complex pagination logic
    - "lib/missive/resources/contact_groups.rb" # Validation logic
    - "lib/missive/resources/contacts.rb" # Validation logic
    - "lib/missive/resources/drafts.rb" # Complex validation for 28 API parameters

Layout/LineLength:
  Max: 130

# Custom cop to forbid em dashes
Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

# Custom em dash detection
Style/CharacterLiteral:
  Enabled: false

# Prevent usage of em dashes (–) in strings and comments
Style/AsciiComments:
  Enabled: true

# This is not a Rails app, blank? method is not available
Rails/Blank:
  Enabled: false

# Allow multi-line block chains for instrumentation patterns
Style/MultilineBlockChain:
  Enabled: false

# Allow single argument dig in tests to verify dig method functionality
Style/SingleArgumentDig:
  Exclude:
    - "spec/**/*"

# Allow intentional test patterns in paginator specs
Lint/UnreachableLoop:
  Exclude:
    - "spec/missive/paginator_spec.rb"

Lint/EmptyBlock:
  Exclude:
    - "spec/missive/paginator_spec.rb"
