plugins:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# Bundler adds frozen_string_literal automatically
Style/FrozenStringLiteralComment:
  Enabled: false

# This is not a Rails app, Time.now is fine
Rails/TimeZone:
  Enabled: false

# Documentation not required for this gem
Style/Documentation:
  Enabled: false

# Allow longer methods and blocks for setup code
Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Max: 50
  Exclude:
    - "spec/**/*"

Metrics/AbcSize:
  Max: 26

Metrics/CyclomaticComplexity:
  Max: 10

Layout/LineLength:
  Max: 130

# Custom cop to forbid em dashes
Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

# Custom em dash detection
Style/CharacterLiteral:
  Enabled: false

# Prevent usage of em dashes (–) in strings and comments
Style/AsciiComments:
  Enabled: true

# This is not a Rails app, blank? method is not available
Rails/Blank:
  Enabled: false

# Allow multi-line block chains for instrumentation patterns
Style/MultilineBlockChain:
  Enabled: false

# Allow single argument dig in tests to verify dig method functionality
Style/SingleArgumentDig:
  Exclude:
    - "spec/**/*"
