name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2'
          - '3.3'
          - '3.4.4'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      
      - name: Run linter
        run: bundle exec rubocop
      
      - name: Run tests
        run: bundle exec rspec
        
      - name: Run mutation tests (Ruby 3.3+)
        if: matrix.ruby >= '3.3'
        run: bundle exec mutant run --since HEAD~1 --fail-fast
