name: Mutation Testing (Nightly)

on:
  schedule:
    - cron: '0 2 * * *'  # Run at 2 AM UTC daily
  workflow_dispatch:  # Allow manual trigger

jobs:
  mutation:
    runs-on: ubuntu-latest
    name: Mutation Test - Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2'
          - '3.3'
          - '3.4.4'

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      
      - name: Run comprehensive mutation tests
        run: bundle exec mutant run
        timeout-minutes: 30
        
      - name: Upload mutation results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: mutation-results-ruby-${{ matrix.ruby }}
          path: tmp/mutant/