name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
      
      - name: Configure gem credentials
        run: |
          mkdir -p ~/.gem
          cat > ~/.gem/credentials << EOF
          ---
          :rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY }}
          EOF
          chmod 0600 ~/.gem/credentials
      
      - name: Build gem
        run: gem build missive.gemspec
      
      - name: Publish gem to RubyGems
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          gem push missive-${VERSION}.gem
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: missive-*.gem
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}